- alias: telegramm_command_code
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.mqtt_command_code
  action:
    - service: script.turn_on
      data_template:
       entity_id: >-
          {%- if states.sensor.mqtt_command_code.state  == '000' -%}
          script.stub
          {%- elif states.sensor.mqtt_command_code.state  == '001' -%}
          script.mqtt_payload_report
          {%- elif states.sensor.mqtt_command_code.state  == '002' -%}
          script.ilife_a4
          {%- elif states.sensor.mqtt_command_code.state  == '003' -%}
          script.boiler_mode_on
          {%- elif states.sensor.mqtt_command_code.state  == '004' -%}
          script.boiler_mode_off
          {%- elif states.sensor.mqtt_command_code.state  == '005' -%}
          script.boiler_manual_on
          {%- elif states.sensor.mqtt_command_code.state  == '006' -%}
          script.boiler_manual_off
          {%- elif states.sensor.mqtt_command_code.state  == '007' -%}
          script.vacancy
          {%- endif -%}
    - delay: 00:00:01
    - service: mqtt.publish
      data_template:
        topic: "states/command"
        payload_template: '000'
        retain: true
        
        
- id: Пинг жизни
  alias: 00_live_ping
  initial_state: true
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id:
        - sensor.time_date
  action:
  - service: mqtt.publish
    data_template:
      topic: "instance/main/sensor/live_ping/state"
      payload: "{{ states('sensor.time_date')}}"
      retain: true   
     