- alias: 00_start
  initial_state: true
  trigger:
  - platform: homeassistant
    event: start
  action:    
    - service: notify.telegram
      data:
        title: 'Отчет'
        message: "Raspberry Pi 3 B+ на связи и статус систем в норме, время - {{ states('sensor.time_date') }}"

        
- alias: 00_backup_everyday
  initial_state: true
  trigger:
    - platform: time
      at: '02:00:00'
  action:
    - service: script.turn_on
      entity_id: script.ha_backup

