- alias: 00_ilife_a4
  initial_state: true
  trigger:
    platform: time
    at: '10:00:00'
  condition:
  - condition: time
    weekday:
      - mon
      - wed
      - fri
  action:    
  - service: notify.telegram
    data:
      title: 'Пылесос'
      message: "Робот пылесос вышел на тропу войны {{ states('sensor.time_date') }}"
  - service: switch.toggle
    entity_id: switch.ilifea4
    

- alias: 00_udpate_entity
  initial_state: true
  trigger:    
    platform: time_pattern
    minutes: '/5'
  action:    
  - service: homeassistant.update_entity
    entity_id:
      -  sensor.last_boot_custom