## Запись последнего движения в коридоре
- alias: 03_motion_time
  initial_state: true
  trigger:
## Движение в коридоре
  - platform: state
    entity_id: binary_sensor.0x00158d00010f8920_occupancy
    to: 'on'
  action: 
  - service: mqtt.publish
    data_template:
      topic: "binary_sensor/158d00010f8920"
      payload: "{{ states('sensor.time_date')}}"
      retain: true