## Возобновление питания на выключателе люстры
- alias: 05_gg_cell_1_power
  initial_state: true
  trigger:       
   - platform: time_pattern
     minutes: '/1'
  condition:
   - condition: template
     value_template: "{{ states('switch.0x00158d00015723f1_switch_right') != 'on' }}"         
  action:
   - service: switch.turn_on
     entity_id: switch.0x00158d00015723f1_switch_right

# Перезагрузка зависшей люстры
- alias: 05_gg_cell_1_reboot
  initial_state: true
  trigger:
  - platform: state
    entity_id: light.yeelight_05_ceiling1
    to: 'unavailable'
    for:
      minutes: 5
  condition:
    condition: numeric_state
    entity_id: sensor.unavailable_now_light
    below: 5
  action:
    - service: mqtt.publish
      data_template:
        topic: "notification/messages"
        payload_template: '0502'
        retain: true
    - service: switch.turn_off
      entity_id: switch.0x00158d00015723f1_switch_right
    

## Люстра 1 гостиная
- alias: 05_gg_cell_1_light
  initial_state: true
  trigger:
## Главный выключатель без нуля
    - platform: state
      entity_id: sensor.0x00158d00015723f1_click
      to: 'right'
## Квадратная кнопка на комоде
    - platform: state
      entity_id: sensor.0x00158d0001e8a244_click
      to: 'single'
## Переворот кубика на 180 градусов
    - platform: state
      entity_id: sensor.0x00158d0001186d82_action
      to: 'flip180' 
## Выключатель возле комода - правая кнопка
    - platform: state
      entity_id: sensor.0x00158d0001f47e10_click
      to: 'right'
## Выключатель на входе в комнату - левая кнопка
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_left_158d00013fc3bc
        click_type: single
  action:    
    - service: script.turn_on
      data_template:
        entity_id: >-
          {%- if states.light.yeelight_05_ceiling1.state == 'off' -%}
          script.05_gg_650_1_on
          {%- else -%}
          script.05_gg_650_1_off
          {%- endif -%}  

## Люстра 2 гостиная
- alias: 05_gg_cell_2_light
  initial_state: true
  trigger:
## Квадратная кнопка  комоде
    - platform: state
      entity_id: sensor.0x00158d0001e8a244_click
      to: 'double'
## Тряска кубика
    - platform: state
      entity_id: sensor.0x00158d0001186d82_action
      to: 'shake' 
## Выключатель возле комода - левая кнопка
    - platform: state
      entity_id: sensor.0x00158d0001f47e10_click
      to: 'left'
  action:    
    - service: script.turn_on
      data_template:
        entity_id: >-
          {%- if states.light.yeelight_05_ceiling2.state == 'off' -%}
          script.05_gg_650_2_on
          {%- else -%}
          script.05_gg_650_2_off
          {%- endif -%}  

## Люстра 1 гостиная - цветовая температура
- alias: 05_gg_cell_1_light_temp
  initial_state: true
  trigger:
## Слайдер
   - platform: state
     entity_id: input_number.yeelight_05_ceiling1_temp
  condition:
   - condition: state
     entity_id: light.yeelight_05_ceiling1
     state: 'on'
  action: 
   - service: light.turn_on
     data_template:
       entity_id: light.yeelight_05_ceiling1
       kelvin: "{{ trigger.to_state.state | int }}"

## Люстра 2 гостиная - цветовая температура
- alias: 05_gg_cell_2_light_temp
  initial_state: true
  trigger:
## Слайдер
   - platform: state
     entity_id: input_number.yeelight_05_ceiling2_temp
  condition:
   - condition: state
     entity_id: light.yeelight_05_ceiling2
     state: 'on'
  action: 
   - service: light.turn_on
     data_template:
       entity_id: light.yeelight_05_ceiling2
       kelvin: "{{ trigger.to_state.state | int }}"

## Полное освещение
- alias: 05_gg_full_light
  initial_state: true
  trigger:
## Подброс кубика
    - platform: state
      entity_id: sensor.0x00158d0001186d82_action
      to: 'fall' 
## Выключатель возле комода - обе кнопки
    - platform: state
      entity_id: sensor.0x00158d0001f47e10_click
      to: 'both'
  action:    
    - service: script.turn_on
      data_template:
        entity_id: >-
          {%- if states.light.yeelight_05_ceiling1.state == 'on' and states.light.yeelight_05_ceiling2.state == 'on' -%}
          script.05_gg_650_1_off, script.05_gg_650_2_off
          {%- else -%}
          script.05_gg_650_full_on
          {%- endif -%}  

## Светильники на стене
- alias: 05_gg_wall_light
  initial_state: true
  trigger:
## Круглая кнопка на комоде
  - platform: state
    entity_id: sensor.0x00158d0001531698_click
    to: 'single'
## Круглая кнопка в прихожей
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d00010b1963
      click_type: single
## Переворот кубика на 90 градусов
  - platform: state
    entity_id: sensor.0x00158d0001186d82_action
    to: 'flip90' 
## Выключатель на входе в комнату - правая кнопка
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_right_158d00013fc3bc
      click_type: single   
  action:
    service: light.toggle
    entity_id: light.aqara_05_wall
    
## Режим просмотра фильмов
- alias: 05_gg_movie_light
  initial_state: true
  trigger:
## Круглая кнопка на комоде
  - platform: state
    entity_id: sensor.0x00158d0001531698_click
    to: 'long'
  action:    
    - service: switch.toggle
      entity_id: switch.movie_mode

## Управление телевизором        
- alias: 05_tv_xiaomi55
  initial_state: true
  trigger:
## Круглая кнопка на комоде
  - platform: state
    entity_id: sensor.0x00158d0001531698_click
    to: 'double'
## Двойной тап кубиком
  - platform: state
    entity_id: sensor.0x00158d0001186d82_action
    to: 'tap' 
  action:
    service: switch.toggle
    entity_id: switch.tv_xiaomi_55

## Люстра на балконе вкл
- alias: 05_gg_balkoon_light_on
  initial_state: true
  trigger:
## Выключатель на входе на балкон
  - platform: state
    entity_id: sensor.0x00158d00010b5aee_click
    to: 'single' 
  - platform: state
    entity_id: binary_sensor.lr_balcony_motion
    to: 'on'
  condition:
   - condition: state
     entity_id: light.66633530807d3a766432
     state: 'off'
  action:
   - service: light.turn_on
     entity_id:
      - light.66633530807d3a766432
     data_template:
        brightness_pct: 100
        kelvin: 5500

## Люстра на балконе выкл
- alias: 05_gg_balkoon_light_off
  initial_state: true
  trigger:
## Выключатель на входе на балкон
  - platform: state
    entity_id: sensor.0x00158d00010b5aee_click
    to: 'single' 
  - platform: state
    entity_id: binary_sensor.0x00158d000449b773_occupancy
    to: 'off'
  condition:
   - condition: state
     entity_id: light.66633530807d3a766432
     state: 'on'
  action:
   - service: light.turn_off
     entity_id:
      - light.66633530807d3a766432

## Люстра на балконе - контроль случайного включения
- alias: 05_gg_balkoon_light_power
  initial_state: true
  trigger:
  - platform: state
    entity_id: light.66633530807d3a766432
    to: 'on' 
    for:
        minutes: 3
  condition:
    - condition: state
      entity_id: binary_sensor.0x00158d000449b773_occupancy
      state: 'off'
  action:
   - service: light.turn_off
     entity_id:
      - light.66633530807d3a766432