## Проветривание
- alias: 05_gg_air_fresh
  initial_state: true
# Проверка каждые 30 минут
  trigger:
    - platform: time_pattern
      minutes: '/30'
  condition:
# Обязательные условия
    condition: and
    conditions:
# День
      - condition: state
        entity_id:  binary_sensor.weekend_time
        state: 'on'
# Закрыто окно  
      - condition: state
        entity_id: binary_sensor.0x00158d00013ed373_contact
        state: 'off'  
# Дополнительные условия 
      - condition: or
        conditions:
          - condition: numeric_state
            entity_id: sensor.05_mi_air_co2a
            above: 2000
          - condition: numeric_state
            entity_id: sensor.05_mi_air_pm25
            above: 150
          - condition: numeric_state
            entity_id: sensor.05_mi_air_tvoc
            above: 3
  action:
  - service: mqtt.publish
    data_template:
      topic: "notification/messages"
      payload_template: '0501'
      retain: true
  - service: script.turn_on
    entity_id: script.talk_05_fresh   
    

