## Включение таймера вентиляции
- alias: 06_bathroom_timer_vent_on
  initial_state: true
  trigger:       
   platform: state
   entity_id: switch.0x00158d0001117040_switch_left
   to: 'on'
  action:
  - service: timer.start
    entity_id: timer.bathroom
    
## Выключение таймера вентиляции
- alias: 06_bathroom_timer_vent_off
  initial_state: true
  trigger:       
   platform: state
   entity_id: switch.0x00158d0001117040_switch_left
   to: 'off'
  action:
  - service: timer.cancel
    entity_id: timer.bathroom

## Включение вентиляции     
- alias: 06_bathroom_vent_on
  initial_state: true
  trigger:
## Влажность более 70 процентов
  - platform: numeric_state
    entity_id: sensor.bt_mean_humidity
    above: 70
## Беспроводный выключатель
  - platform: state
    entity_id: sensor.0x00158d000238a140_action
    to: 'single_right'
  condition:
  - condition: state
    entity_id: switch.control_mode
    state: 'on'  
  - condition: state
    entity_id: switch.0x00158d0001117040_switch_left
    state: 'off'
  - condition: time
    after: '08:00:00'
    before: '22:00:00'
  action:
  - service: switch.turn_on
    entity_id: switch.0x00158d0001117040_switch_left

## Выключение вентиляции 
- alias: 06_bathroom_vent_off
  initial_state: true
  trigger:    
## Завершение таймера
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.bathroom
## Беспроводный выключатель
  - platform: state
    entity_id: sensor.0x00158d000238a140_action
    to: 'single_right'
  condition:
  - condition: state
    entity_id: switch.control_mode
    state: 'on'  
  - condition: state
    entity_id: switch.0x00158d0001117040_switch_left
    state: 'on'
  action:
  - service: switch.turn_off
    entity_id: switch.0x00158d0001117040_switch_left

## Запись последнего движения в ванной
- alias: 06_bathroom_motion_time
  initial_state: true
  trigger:
## Движение в ванной
  - platform: state
    entity_id: binary_sensor.0x00158d0001e547a3_occupancy
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.control_mode
    state: 'on' 
  action: 
  - service: mqtt.publish
    data_template:
      topic: "binary_sensor/158d0001e547a3"
      payload: "{{ states('sensor.time_date')}}"
      retain: true