- alias: 07_dd_heater
  id: 'Режим обогрева детской Д'
  initial_state: true
  trigger:
    - platform: homeassistant
      event: start
    - platform: time_pattern
      minutes: '/5'
    - platform: state
      entity_id:
        - binary_sensor.dd_heat
  action:
    - service: script.turn_on
      data_template:
        entity_id: >-
          {%- if states.binary_sensor.dd_heat.state == 'on' -%}
          script.dd_home
          {%- elif states.binary_sensor.dd_heat.state == 'off' -%}
          script.dd_away
          {%- endif -%}  