## Возобновление питания на рабочем столе
- alias: 08_da_relay_power
  initial_state: true
  trigger:       
   - platform: time_pattern
     minutes: '/1'
  condition:
   - condition: template
     value_template: "{{ states('switch.0x00158d0002d7bb2b_switch_l1') != 'on' }}"
   - condition: state
     entity_id: switch.control_mode
     state: 'on'
  action:
   - service: switch.turn_on
     entity_id: switch.0x00158d0002d7bb2b_switch_l1

# Проектор
- alias: 08_smart_projector
  initial_state: true
  trigger:
## Пульт ДУ на три кнопки, третья
  - platform: state
    entity_id: sensor.0x60a423fffe942cf2_action
    to: '3_single'
## Квадратная возле кровати
  - platform: state
    entity_id: sensor.0x00158d0001e8a244_action
    to: 'single'
  condition:
  - condition: state
    entity_id: switch.control_mode
    state: 'on'  
  action:
  - service: light.toggle
    entity_id: light.da_proektor
  - delay: 00:00:03

## Включение ночника по движению
- alias: 08_da_light_auto
  initial_state: true
  trigger:
## Условия для срабатывания ночника
  - platform: state
    entity_id: binary_sensor.0x00158d00016d56f5_occupancy
    to: 'on'
## Условия для срабатывания ночника
  condition:
    - condition: state
      entity_id: binary_sensor.da_nightlight
      state: 'on'
    - condition: state
      entity_id: switch.control_mode
      state: 'on'
  action:
  - service: light.turn_on
    entity_id: 
     - light.gateway_light_f0b429cc1f11
     - light.philips_08_bedside
    data_template:
       brightness_pct: 50
       rgb_color: [0, 100, 255]
  - delay: 00:00:15
  - service: light.turn_off
    entity_id: 
     - light.gateway_light_f0b429cc1f11
     - light.philips_08_bedside

## Управление освещением
- alias: 08_da_light
  initial_state: true
  trigger:
## Выключатель на входе
  - platform: state
    entity_id: sensor.0x00158d00010b5c6e_action
    to: 'single'
## Круглая кнопка возле кровати
  - platform: state
    entity_id: sensor.0x00158d000155d2fb_click
    to: 'single'
## Пульт ДУ на три кнопки, первая
  - platform: state
    entity_id: sensor.0x60a423fffe942cf2_action
    to: '1_single'
## Круглая кнопка на столе
  - platform: state
    entity_id: sensor.0x00158d000186d9a9_click
    to: 'single'
  condition:
    - condition: state
      entity_id: switch.control_mode
      state: 'on'
  action:    
    - service: script.turn_on
      data_template:
        entity_id: >-
         {%- if states.light.aqara_08_ceiling.state == 'off' and states.light.yeelight_08_strip.state == 'off' and states("binary_sensor.tod_long_day") == 'on' -%}
         script.08_da_ceiling_on
         {%- elif states.light.aqara_08_ceiling.state == 'off' and states.light.yeelight_08_strip.state == 'off' and states("binary_sensor.tod_early_night") == 'on' -%}
         script.08_da_nightlight
         {%- elif states.light.aqara_08_ceiling.state == 'off' and states.light.yeelight_08_strip.state == 'on' -%}
         script.08_da_nightlight_off
         {%- elif states.light.aqara_08_ceiling.state == 'on' and states.light.yeelight_08_strip.state == 'on' -%}
         script.08_da_nightlight_off
         {%- elif states.light.aqara_08_ceiling.state == 'on' and states.light.yeelight_08_strip.state == 'off' -%}
         script.08_da_ceiling_off
         {% endif %}    
    - delay: 00:00:03

## Управление циклической подсветкой
- alias: 08_da_light_circle
  initial_state: true
  trigger:
## Пульт ДУ на три кнопки, вторая
  - platform: state
    entity_id: sensor.0x60a423fffe942cf2_action
    to: '2_single'
## Круглая кнопка возле кровати
  - platform: state
    entity_id: sensor.0x00158d000155d2fb_click
    to: 'double'
## Круглая кнопка на столе
  - platform: state
    entity_id: sensor.0x00158d000186d9a9_click
    to: 'double'
## Кубик
  - platform: state
    entity_id: sensor.0x00158d00028f6fe6_action
    to: 'shake'
  condition:
    - condition: state
      entity_id: switch.control_mode
      state: 'on'
  action:    
    - service: script.turn_on
      data_template:
        entity_id: >-
         {%- if states.light.yeelight_08_strip.state == 'off' -%}
         script.08_da_light_circle_1
         {%- elif states.light.yeelight_08_strip.state == 'on' -%}
         script.08_da_nightlight_off
         {% endif %}
    - delay: 00:00:03

# Выключение всего освещения
- alias: 08_da_alllight_off
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.0x00158d00028f6fe6_action
    to: 'fall'
  condition:
    - condition: state
      entity_id: switch.control_mode
      state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.08_da_lightoff
      
# # Управление ночным режимы камеры 
# - alias: 08_da_xiaofang
#   initial_state: true
#   trigger:
#     platform: state
#     entity_id:
#       - sensor.0x04cf8cdf3c78ca91_illuminance
#   action:
#     service_template: >-
#       {% set illum = states('sensor.0x04cf8cdf3c78ca91_illuminance') | float %}
#       {% if illum >= 5000 %}
#         switch.turn_off
#       {% elif illum < 5000 %}
#         switch.turn_on
#       {% endif %}
#     entity_id: switch.xiaofang1s_night_mode
      
## Запись последнего движения в детской А
- alias: 08_da_motion_time
  initial_state: true
  trigger:
## Движение в детской А
  - platform: state
    entity_id: binary_sensor.0x00158d00016d56f5_occupancy
    to: 'on'
  condition:
    - condition: state
      entity_id: switch.control_mode
      state: 'on'
  action: 
  - service: mqtt.publish
    data_template:
      topic: "binary_sensor/158d00016d56f5"
      payload: "{{ states('sensor.time_date')}}"
      retain: true