- platform: systemmonitor
  resources:
  - type: processor_use
  - type: disk_use_percent
    arg: /
  - type: memory_use_percent
  - type: last_boot
  - type: disk_free
    arg: /
    
- platform: filesize
  file_paths:
     - /config/home-assistant_v2.db
     
- platform: sql
  db_url: !secret db_link
  queries:
    - name: maria_db
      query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1048576, 2) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
      column: 'value'
      unit_of_measurement: MB

# - platform: influxdb
#   host: a0d7b954-influxdb
#   port: 8086
#   username: homeassistant
#   password: homeassistant
#   queries:
#   - name: InfluxDB Database Size
#     unit_of_measurement: MB
#     value_template: '{{ (value | float / 1024 /1024) | round(1) }}'
#     group_function: mean
#     measurement: '"monitor"."shard"'
#     database: _internal
#     where: 'time > now() - 1m AND "database"=''homeassistant'''
#     field: diskBytes 
    
- platform: command_line
  name: cpu_temp
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ (value | multiply(0.001)) | round(1) }}'

- platform: version
  name: current_ha
  scan_interval: 1800

  
- platform: template
  sensors:
    version:
      friendly_name: 'Последняя версия - '
      value_template: '{{ states.binary_sensor.updater.attributes["newest_version"] }}'
      
- platform: rpi_power
  text_state: true



